document.addEventListener('DOMContentLoaded',()=>{
  if(window.lucide)lucide.createIcons();
  const box=document.querySelector('#cart-items'),empty=document.querySelector('#empty-cart'),form=document.querySelector('#checkout-form'),modal=document.querySelector('#pix-modal');
  const money=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),get=()=>JSON.parse(localStorage.getItem('arteNossaCart')||'[]'),save=c=>{localStorage.setItem('arteNossaCart',JSON.stringify(c));render()};
  const total=()=>get().reduce((sum,i)=>sum+i.price*i.qty,0)+(get().length?18:0);
  function render(){const cart=get();box.innerHTML='';cart.forEach(item=>{const row=document.createElement('div');row.className='cart-item';row.innerHTML=`<img src="../${item.image}" alt=""><div><h3>${item.name}</h3><small>por ${item.artisan}</small><div class="qty"><button data-act="minus">−</button><span>${item.qty}</span><button data-act="plus">+</button></div></div><div><p class="price">${money(item.price*item.qty)}</p><button data-act="remove" aria-label="Remover"><i data-lucide="trash-2"></i></button></div>`;row.querySelectorAll('button').forEach(b=>b.onclick=()=>{let c=get(),found=c.find(x=>x.id===item.id);if(b.dataset.act==='plus')found.qty++;if(b.dataset.act==='minus')found.qty--;if(b.dataset.act==='remove'||found.qty<1)c=c.filter(x=>x.id!==item.id);save(c)});box.append(row)});const sub=cart.reduce((sum,i)=>sum+i.price*i.qty,0),shipping=cart.length?18:0;document.querySelector('#item-count').textContent=`${cart.reduce((n,i)=>n+i.qty,0)} itens`;document.querySelector('#subtotal').textContent=money(sub);document.querySelector('#shipping').textContent=money(shipping);document.querySelector('#total').textContent=money(sub+shipping);empty.hidden=cart.length>0;form.querySelector('.finish').disabled=!cart.length;if(window.lucide)lucide.createIcons()}
  document.querySelector('#cep').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').replace(/(\d{5})(\d)/,'$1-$2'));
  let timerId;function openPix(){document.querySelector('#pix-total').textContent=money(total());modal.hidden=false;document.body.style.overflow='hidden';let seconds=600;clearInterval(timerId);timerId=setInterval(()=>{seconds--;document.querySelector('#pix-timer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds<=0)clearInterval(timerId)},1000);if(window.lucide)lucide.createIcons()}
  function closePix(){modal.hidden=true;document.body.style.overflow='';clearInterval(timerId)}
  function success(){closePix();document.querySelector('#order-code').textContent=`Pedido #AN${Date.now().toString().slice(-6)}`;document.querySelector('#success').hidden=false;localStorage.removeItem('arteNossaCart');if(window.lucide)lucide.createIcons()}
  form.onsubmit=e=>{e.preventDefault();if(!get().length)return;document.querySelector('input[name="payment"]:checked').value==='pix'?openPix():success()};
  document.querySelector('.pix-close').onclick=closePix;modal.onclick=e=>{if(e.target===modal)closePix()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closePix()});
  document.querySelector('#copy-pix').onclick=async()=>{const text=document.querySelector('#pix-code').textContent;try{await navigator.clipboard.writeText(text)}catch{const area=document.createElement('textarea');area.value=text;document.body.append(area);area.select();document.execCommand('copy');area.remove()}document.querySelector('#copy-pix span').textContent='Copiado!'};
  document.querySelector('#pix-confirm').onclick=success;render();
});
